version: '3.1'
services:

  mongo:
    image: mongo:4.2.3-bionic
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: test123
    volumes:
      - "./etc/mongod.conf:/etc/mongod.conf"
      - "./data/db:/data/db"
      - "./var/log/mongodb/mongod.log:/var/log/mongodb/mongod.log"

  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    restart: always
    ports:
      - 27018:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: test123

#  mongo-client:
#    image: mongoclient/mongoclient:2.2.0
#    depends_on:
#      - mongo
#    restart: always
#    ports:
#      - 3000:3000
#    environment:
#      MONGO_URL: "mongodb://root:test123@mongo:27017"
